export const initialStudies = [
  {
    id: 1,
    title: 'React 입문 스터디',
    category: '코딩',
    status: '모집 중',
    maxMembers: 6,
    currentMembers: 3,
    method: '온라인',
    schedule: '화/목 20:00',
    location: 'Zoom',
    description: 'React 기본 문법부터 컴포넌트 설계와 간단한 프로젝트 제작까지 함께 공부합니다.',
    tags: ['React', '프론트엔드', '초보환영'],
    createdAt: '2026-05-01',
  },
  {
    id: 2,
    title: '토익 800 목표반',
    category: '영어',
    status: '모집 중',
    maxMembers: 8,
    currentMembers: 5,
    method: '오프라인',
    schedule: '월/수 18:30',
    location: '중앙도서관 3층 스터디룸',
    description: 'LC와 RC를 번갈아 풀고 매주 단어 시험과 오답 리뷰를 진행합니다.',
    tags: ['TOEIC', '영어', '단어시험'],
    createdAt: '2026-04-28',
  },
  {
    id: 3,
    title: '정보처리기사 필기 스터디',
    category: '자격증',
    status: '마감',
    maxMembers: 5,
    currentMembers: 5,
    method: '혼합',
    schedule: '토 10:00',
    location: '공학관 204호 및 Discord',
    description: '기출 문제를 중심으로 개념 정리와 과목별 예상 문제 풀이를 함께합니다.',
    tags: ['정보처리기사', '기출', '자격증'],
    createdAt: '2026-04-20',
  },
  {
    id: 4,
    title: '운영체제 전공 스터디',
    category: '전공',
    status: '모집 중',
    maxMembers: 6,
    currentMembers: 2,
    method: '오프라인',
    schedule: '금 16:00',
    location: '공학관 512호',
    description: '운영체제 수업 내용을 복습하고 프로세스, 메모리, 파일 시스템을 발표 형식으로 정리합니다.',
    tags: ['운영체제', '전공', '발표'],
    createdAt: '2026-04-18',
  },
  {
    id: 5,
    title: '취업 포트폴리오 스터디',
    category: '취업',
    status: '모집 중',
    maxMembers: 4,
    currentMembers: 1,
    method: '온라인',
    schedule: '일 21:00',
    location: 'Google Meet',
    description: '개인 포트폴리오와 자기소개서를 매주 리뷰하고 개선 과제를 공유합니다.',
    tags: ['포트폴리오', '자소서', '취업준비'],
    createdAt: '2026-04-15',
  },
  {
    id: 6,
    title: '발표 연습 스터디',
    category: '기타',
    status: '모집 중',
    maxMembers: 7,
    currentMembers: 4,
    method: '오프라인',
    schedule: '수 19:00',
    location: '학생회관 세미나실',
    description: '짧은 발표를 준비해 서로 피드백하고 말하기 습관과 자료 구성을 개선합니다.',
    tags: ['발표', '피드백', '커뮤니케이션'],
    createdAt: '2026-04-10',
  },
];
